import { Sidebar } from "@/components/layout/sidebar";
import { TwIndicator } from "@/components/tw-indicator";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={cn(inter.className, "dark")}
        style={{ colorScheme: "dark" }}
      >
        <body className={`${inter.className} min-h-screen`}>
          {/* <Navbar /> */}

          <main className="flex flex-row">
            <Sidebar />
            <section className="flex min-h-screen flex-1 flex-col items-center px-6 pb-10 pt-24 max-md:pb-32 sm:px-10">
              <div className="w-full">{children}</div>
            </section>
          </main>

          {/* <Bottombar /> */}
          <TwIndicator />
        </body>
      </html>
    </ClerkProvider>
  );
}
