import { TwIndicator } from "@/components/tw-indicator";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(inter.className, "dark")}
      style={{ colorScheme: "dark" }}
    >
      <head />
      <body className="min-h-screen antialiased">
        {children}
        <TwIndicator />
      </body>
    </html>
  );
}
