export const theme = {
  form: "text-black dark:text-[#fafafa]",
  formButtonPrimary:
    "bg-sky-500 border border-sky-500 border-solid hover:bg-sky-600",
  socialButtonsBlockButton:
    "bg-white border-gray-200 hover:bg-neutral-100 dark:hover:bg-sky-500 hover:border-black dark:hover:border-sky-500 text-gray-600 dark:hover:text-neutral-50",
  socialButtonsBlockButtonText: "font-semibold",
  formButtonReset:
    "bg-white border border-solid border-gray-200 hover:bg-transparent hover:border-black text-gray-500 hover:text-black",
  membersPageInviteButton:
    "bg-black border border-black border-solid hover:bg-white hover:text-black",
  card: "bg-[#fafafa] dark:bg-zinc-900",
  headerTitle: "text-black dark:text-neutral-50",
  headerSubtitle: "text-black dark:text-neutral-300",
  dividerLine: "bg-black dark:bg-neutral-300",
  dividerText: "text-black dark:text-neutral-300",
  formFieldLabel: "text-black dark:text-neutral-300",
  footerActionText: "text-black dark:text-neutral-300",
  navbarButton: "text-black dark:text-neutral-50",
  profileSectionTitleText: "text-black dark:text-neutral-50",
  profileSectionContent: "text-black dark:text-neutral-50",
  profileSectionPrimaryButton: "text-sky-500",
  accordionTriggerButton: "text-black dark:text-neutral-300",
  userPreviewSecondaryIdentifier: "text-black dark:text-neutral-300",
  accordionContent: "text-black dark:text-neutral-300",
  breadcrumbsItem: "text-black dark:text-neutral-300",
  breadcrumbsItemDivider: "text-black dark:text-neutral-300",
  modalCloseButton: "text-black dark:text-neutral-300",
  userPreview: "text-black dark:text-neutral-50",
  userButtonPopoverActionButtonIcon: "text-black dark:text-neutral-300",
  userButtonPopoverActionButtonText: "text-black dark:text-neutral-300",
  formFieldWarningText: "text-black dark:text-neutral-300",
  formFieldSuccessText: "text-black dark:text-neutral-300",
  formHeaderTitle: "text-black dark:text-neutral-50",
  identityPreviewText: "text-black dark:text-neutral-50",
  formHeaderSubtitle: "text-black dark:text-neutral-300",
  otpCodeFieldInput: "text-black dark:text-neutral-300 dark:border-neutral-300",
};
