import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "../globals.css";
import { TwIndicator } from "@/components/tw-indicator";
import { cn } from "@/lib/utils";
import { theme } from "@/lib/clerk-theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Applicare - Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        variables: { colorPrimary: "#0ea5e9" },
        elements: theme,
      }}
    >
      <html
        lang="en"
        className={cn(inter.className, "dark")}
        style={{ colorScheme: "dark" }}
      >
        <body className="flex w-full h-screen">
          <div className="w-full flex items-center justify-center lg:w-1/2 bg-white dark:bg-zinc-800">
            {children}
          </div>
          <div className="hidden relative w-1/2 h-full lg:flex items-center justify-center bg-gray-100 dark:bg-zinc-900">
            <div className="w-60 h-60 rounded-full bg-gradient-to-tr from-[#38bdf8] to-[#075985] animate-pulse" />
            <div className="w-full h-1/2 absolute bottom-0 bg-gray-100/10  dark:bg-zinc-900/10 backdrop-blur-lg" />
          </div>
          <TwIndicator />
        </body>
      </html>
    </ClerkProvider>
  );
}
